<?php
return [
    'siteKey' => env('SHUGOI_SITE_KEY', ''),
    'secret' => env('SHUGOI_SECRET', ''),
    'signingSecret' => env('SHUGOI_SIGNING_SECRET'),
    'allowlist' => ['/api', '/legal'],
    'headlessPatterns' => \Shugoi\Config::DEFAULT_HEADLESS_PATTERNS,
    'botWhitelist' => \Shugoi\Config::DEFAULT_BOT_WHITELIST,
    'baseUrl' => env('SHUGOI_BASE_URL', 'https://shugoi.com/api/v1'),
    'internalUrl' => env('SHUGOI_INTERNAL_URL'),
    'debug' => env('SHUGOI_DEBUG', false),
    'autoInject' => true,
    'restrictedAccess' => false,
    'extraDirectives' => [],
    'csp' => true,
    'blockStatus' => 403,
    'locale' => null,
    'blockPage' => null,
    'splitRender' => true,
    'multiProcess' => true,
    'browserTransport' => env('SHUGOI_BROWSER_TRANSPORT', 'http'),
    'renderStore' => env('SHUGOI_RENDER_STORE', 'memory'),
    'renderStorePath' => env('SHUGOI_RENDER_STORE_PATH'),
    'websocketBind' => env('SHUGOI_RENDER_WS_BIND', '127.0.0.1'),
    'websocketPort' => (int) env('SHUGOI_RENDER_WS_PORT', 8787),
    'publicOrigin' => env('SHUGOI_PUBLIC_ORIGIN'),
    'powWebSocketUrl' => env('SHUGOI_POW_WEBSOCKET_URL', '/__sg_challenge/ws'),
    'powReceiptStorePath' => env('SHUGOI_POW_RECEIPT_STORE_PATH'),
    'verifyBots' => true,
    'powDifficulty' => (int) env('SHUGOI_POW_DIFFICULTY', 14),
    'powTtlMs' => 60000,
    'powOkTtlMs' => 2592000000,
];
